name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print Node Version
        run: node -v

      - name: Print Working Directory
        run: pwd
